[package]
name = "shot-paint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5.0"
image = "0.25"
winit = "0.30.4"
pixels = "0.13.0"
